import React, { useEffect } from 'react';
import { ArrowLeft } from 'lucide-react';

interface TermsOfServicePageProps {
  onBack: () => void;
}

export const TermsOfServicePage: React.FC<TermsOfServicePageProps> = ({ onBack }) => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="pt-32 pb-20 min-h-screen bg-deep-black text-white">
      <div className="container mx-auto px-6 max-w-4xl">
        <button 
          onClick={onBack}
          className="group flex items-center gap-2 text-white/50 hover:text-electric-blue mb-12 transition-colors uppercase tracking-widest text-xs font-bold"
        >
          <ArrowLeft size={16} className="group-hover:-translate-x-1 transition-transform" /> Back to Home
        </button>

        <h1 className="font-display text-5xl md:text-7xl font-bold mb-12 tracking-tighter">
          Terms of <span className="text-transparent bg-clip-text bg-gradient-to-r from-electric-blue to-teal-400">Service</span>
        </h1>

        <div className="space-y-12 text-white/70 leading-relaxed font-light text-lg">
          <section>
            <h2 className="text-2xl font-display font-bold text-white mb-4">1. Acceptance of Terms</h2>
            <p>
              By accessing and using the NewGen Marketing website and services, you accept and agree to be bound by the terms and provision of this agreement. In addition, when using these particular services, you shall be subject to any posted guidelines or rules applicable to such services.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-display font-bold text-white mb-4">2. Description of Service</h2>
            <p>
              NewGen Marketing provides social media management, content creation, digital marketing strategy, and related services. We reserve the right to modify, suspend, or discontinue the service at any time without notice.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-display font-bold text-white mb-4">3. Intellectual Property</h2>
            <p>
              All content generated by NewGen Marketing specifically for a client remains the intellectual property of the client upon full payment. However, NewGen Marketing retains the right to use such works in our portfolio and for self-promotional purposes unless a specific non-disclosure agreement (NDA) is signed. The underlying tools, methodologies, and pre-existing frameworks remain the property of NewGen Marketing.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-display font-bold text-white mb-4">4. Client Responsibilities</h2>
            <p>
              You agree to provide all necessary assets, credentials, and information required for us to perform our services in a timely manner. You represent that you have the right to use any images, trademarks, or content you provide to us.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-display font-bold text-white mb-4">5. Payment and Refunds</h2>
            <p>
              Services are billed according to the agreed-upon proposal or package. Payments are due as specified in your invoice. We generally do not offer refunds for services once work has commenced, but we will work with you to ensure satisfaction within the scope of the original agreement.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-display font-bold text-white mb-4">6. Limitation of Liability</h2>
            <p>
              In no event shall NewGen Marketing be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your use of our services.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-display font-bold text-white mb-4">7. Changes to Terms</h2>
            <p>
              We reserve the right to update or modify these Terms of Service at any time without prior notice. Your continued use of the website or services following any such changes constitutes your agreement to follow and be bound by the Terms of Service as changed.
            </p>
          </section>

          <div className="pt-12 border-t border-white/10 text-sm text-white/40">
            Last Updated: {new Date().toLocaleDateString()}
          </div>
        </div>
      </div>
    </div>
  );
};